new method to import and run binaries
Debian is utterly broken when it comes to startup policy
not even the workaround by Evgeni Golov in bug 804018 works well
so we extract the binaries by hand and run them from inside run/
this gives to Dowse full control on daemons and avoids system-wide
installation of their packages.

diff --git a/daemons/privoxy b/daemons/privoxy
--- a/daemons/privoxy
+++ b/daemons/privoxy
@@ -1,5 +1,25 @@
 #!/usr/bin/env zsh
 
+privoxy-extract() {
+    fn privoxy-extract
+
+    # check if already imported
+    [[ -r $R/run/privoxy ]] && return 0
+
+    deb-download privoxy
+
+    cp $R/tmp/usr/sbin/privoxy $R/run || {
+        error "privoxy binary not found"
+        return 1 }
+
+    act "privoxy binary imported"
+    func "`ls $R/tmp`"
+
+    rm -rf $R/tmp
+
+    func "`file $R/run/privoxy`"
+}
+
 privoxy-conf() {
     # Privoxy configuration template
     func "generating privoxy configuration"
@@ -51,9 +71,9 @@ privoxy-start() {
 
     act "starting privoxy: $conf"
     if [[ -z $root ]]; then
-        privoxy --pidfile $pidfile $conf.real
+        $R/run/privoxy --pidfile $pidfile $conf.real
     else
-        privoxy --user $dowse_uid --pidfile $pidfile $conf.real
+        $R/run/privoxy --user $dowse_uid --pidfile $pidfile $conf.real
     fi
 
 }
diff --git a/daemons/squid3 b/daemons/squid3
--- a/daemons/squid3
+++ b/daemons/squid3
@@ -1,9 +1,41 @@
 #!/usr/bin/env zsh
 
+
+squid-extract() {
+    fn extract-squid
+
+    [[ -r $R/run/squid3 ]] && return 0
+
+    deb-download squid3
+    deb-download squid3-common
+    deb-download libecap2
+
+    cp $R/tmp/usr/sbin/squid3 $R/run \
+        && cp $R/tmp/usr/lib/libecap.so.2.0.0       $R/run/libecap.so.2 \
+        && cp $R/tmp/usr/share/squid3/mime.conf     $R/run/squid.mime \
+        && cp $R/tmp/usr/lib/squid3/unlinkd         $R/run/squid.unlinkd \
+        && cp $R/tmp/usr/lib/squid3/log_file_daemon $R/run/squid.logfiled \
+        && cp -r $R/tmp/usr/share/squid3/icons      $R/run/squid.icons \
+            || {
+            error "squid3 binaries not found"
+            return 1 }
+
+    act "squid3 binaries imported"
+    func "`ls $R/tmp`"
+
+    rm -rf $R/tmp
+
+    func "`file $R/run/squid3`"
+}
+
 squid-conf() {
     # Squid2 configuration template
     func "generating base configuration for squid3"
     cat <<EOF
+mime_table $R/run/squid.mime
+unlinkd_program $R/run/squid.unlinkd
+logfile_daemon $R/run/squid.logfiled
+icon_directory $R/run/squid.icons
 cache_effective_user $dowse_uid
 cache_store_log none
 
@@ -92,6 +124,11 @@ never_direct allow all
 
 EOF
 
+    [[ $DEBUG = 0 ]] || {
+        cat <<EOF
+debug_options rotate=9 ALL,3
+EOF
+    }
 }
 
 squid-start() {
@@ -107,9 +144,10 @@ squid-start() {
     # setuidgid $dowseuid squid3 -z -f "$1"
     # launch the squid
     if [[ -z $root ]]; then
-        squid3 -f $conf $*
+        LD_LIBRARY_PATH=$R/run $R/run/squid3 -f $conf $*
     else
-        setuidgid $dowse_uid squid3 -f $conf $*
+        LD_LIBRARY_PATH=$R/run setuidgid $dowse_uid $R/run/squid3 -f $conf $*
+#        LD_LIBRARY_PATH=$R/run $R/run/squid3 -f $conf $*
     fi
 
 }
@@ -123,9 +161,10 @@ squid-stop() {
     pid=`cat $pidfile`
     act "Stopping squid ($pid)"
     if [[ -z $root ]]; then
-        squid3 -f $R/run/squid.conf -k kill
+        LD_LIBRARY_PATH=$R/run $R/run/squid3 -f $R/run/squid.conf -k kill
     else
-        setuidgid $dowse_uid squid3 -f $R/run/squid.conf -k kill
+        LD_LIBRARY_PATH=$R/run setuidgid $dowse_uid $R/run/squid3 -f $R/run/squid.conf -k kill
+#        LD_LIBRARY_PATH=$R/run $R/run/squid3 -f $R/run/squid.conf -k kill
     fi
 
     waitpid $pid
